#!/bin/bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -eu


# -- Set program name and version.

TOOL_NAME="Nitrux Update System Tool"
UPCP_VERSION="$(md5sum /usr/bin/nuts-cru | cut -c -32)"


# -- Print informative messages to stderr.

puts_info() {
	if [ -n "$1" ]; then
		printf "%s: \e[34mInfo:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
	fi
}


# -- Print success messages to stderr.

puts_success() {
	if [ -n "$1" ]; then
		printf "%s: \e[32mSuccess:\e[0m %s\n" "$TOOL_NAME" "$*" >&2
	fi
}


# -- Print error messages to stderr.

puts_error() {
	if [ -n "$1" ]; then
		printf "%s: \e[31mError:\e[0m %b\n" "$TOOL_NAME" "$*" >&2
	fi
}


# -- Print messages or text using multiple lines to stderr.

print_message() {
	if [ -n "$1" ]; then
		printf "%s\n" "$@" >&2
	fi
}


# -- Define the path of the nuts configuration file.

CONFIG_FILE="/etc/nuts.conf"


# -- Load values from configuration file.
# -- Include fix for SC1090 – ShellCheck.

if [[ ! -f $CONFIG_FILE ]]; then
    puts_error "$TOOL_NAME configuration file not found!, quitting." 2>&1
    exit 1
else
	puts_success "Success! $TOOL_NAME configuration file found, continuing..."
	# shellcheck source=/dev/null
	. "$CONFIG_FILE"
fi


# -- Functions.

dl_file() {
    local FILE_URL="$1"
    local FILE_NAME
    FILE_NAME=$(basename "$FILE_URL")
    local FILE_PATH="/tmp/$FILE_NAME"

    [ -f "$FILE_PATH" ] && rm "$FILE_PATH"

    if ! command -v axel >/dev/null 2>&1; then
        puts_error "axel command not found, unable to download file."
        return 1
    fi

    if ! curl --output /dev/null --silent --head --fail "$FILE_URL"; then
        puts_error "File URL is not accessible, unable to download file."
        return 1
    fi

    if ! axel -o "/tmp" -n 10 "$FILE_URL"; then
        puts_error "Failed to download file."
        return 1
    fi
}


bak_cc() {
    if [ ! -d "$NUTS_DIR_BAK" ]; then
        return 1
    fi

    if ! [[ "$BACKUPS_TO_KEEP" =~ ^[0-9]+$ ]]; then
        return 1
    fi

    find "$NUTS_DIR_BAK" -maxdepth 1 -type f -exec rm {} +
    find "$NUTS_DIR_BAK" -maxdepth 1 -type f | sort -r | tail -n +$((BACKUPS_TO_KEEP + 1)) | xargs --no-run-if-empty rm
}


unmount_directory() {
  local DIRECTORY="$1"

  if mountpoint -q "$DIRECTORY"; then
    puts_info "Unmounting: $DIRECTORY"
    umount "$DIRECTORY"
  else
    puts_info "Directory is not mounted: $DIRECTORY"
  fi
}


# -- Mount the devices filesystem.
# -- Check if /dev is already mounted.

if mountpoint -q /dev; then
    puts_info "/dev is already mounted. Unmounting..."
    umount /dev
fi

puts_info "Mounting /dev..."
mount -t devtmpfs dev /dev


# -- Mount NX_HOME partition.
# -- When entering the chroot, only the root partition is mounted, but that's likely to not have enough storage.
# -- So, let's use the /home partition. We're discovering NX_HOME by the LABEL of the partition.

HOME_PARTITION=$(findfs LABEL=NX_HOME)

if mountpoint -q /home; then
    puts_info "/home is already mounted. Unmounting..."
    umount /home
fi

puts_info "Mounting $HOME_PARTITION to /home..."
mount -t auto "$HOME_PARTITION" /home


# -- Variables.

CURRENT_DIST=$(awk -F'=' '/VERSION_CODENAME/{print $NF}' /etc/os-release)
OUTPUT_FILE=$(mktemp)

#   ====== START ======

# -- Flag parsing.

for cmd; do
	case "$cmd" in
		-v | --version)
			print_message "$TOOL_NAME" \
				"" \
				"Version (update component): $UPCP_VERSION." \
				"" \
				"The license used for this file and its contents is: BSD-3-Clause." \
				"" \
				"Authors:" \
				"" \
				"    Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>" \
				"" \
				"(c) $FECHA Some Rights Reserved. Made by $VENDOR"

			exit
			;;
	esac
done


# -- Create the directories for nuts.
# -- Create working directories in /home since this partition will likely have more space than the root partition.

DIRECTORIES=("$NUTS_DIR_BAK" "$NUTS_DIR_XFS" "$NUTS_DIR_DLS" "$NUTS_DIR_SQS")

for DIR in "${DIRECTORIES[@]}"; do
  if [[ ! -d "$DIR" ]]; then
    puts_error "Directory '$DIR' does not exist. Creating the directory..."
    if ! mkdir -p "$DIR"; then
      puts_error "Failed to create directory '$DIR'. Exiting..."
      exit 1
    fi
    puts_info "Directory '$DIR' created successfully."
  fi
done

puts_info "All required directories exist. Continuing."


# -- Run the backup cleaner.
# -- Only keep the amount of backups defined in nuts.conf.

puts_info "Cleaning older backups, continuing..."
bak_cc


# -- Create the backup using SquashFS.
# -- We assume that the /home partition is on an internal storage device (SATA or NVME), but one can never know, so run sync to flush the write cache.
# -- To exclude a file specifiy the full path, i.e., /etc/shadow
# -- To exclude a directory and its contents specify the path of the directory, i.e., /home/
# -- To include a directory but exclude its contents specify the path of the directory and use an asterisk, i.e., /home/*
# -- To include a directory and its contents or a file, don't add either to the list.

puts_info "Creating backup of ${CURRENT_DIST^}, continuing..."

BACKUP_FILE="$NUTS_DIR_BAK/nuts-backup-$DATE_BACKUP_FILE.squashfs"

mksquashfs / "$BACKUP_FILE" \
	-quiet \
	-not-reproducible \
	-e /boot/* \
	-e /dev/* \
	-ef /etc/shadow \
	-e /home/ \
	-e /proc/ \
	-e /run/* \
	-e /sys/* \
	-e /tmp/* \
	-e /var/{cache,lib,local,lock,log,mail,opt,run,spool,tmp}/ \
	-comp zstd \
	-Xcompression-level 22 \
	-b 1048576

md5sum "$BACKUP_FILE" > "$NUTS_DIR_BAK/nuts-backup.md5sum"

sync

puts_success "Success! Backup has been created."


# -- Download the OTA SquashFS with aria2c using the BitTorrent protocol.
# -- Check if the OTA SquashFS already exists so it's not downloaded again. If an OTA file was downloaded then rename it.
# -- However, If the OTA file found doesn't match the checksum, it will still cause the utility to exit at a later stage.
# -- Use the magnet link from the query file.
# -- Magnet link is provided by FOSS Torrents https://fosstorrents.com/distributions/nitrux/#downloads.

OTA_FILE="$NUTS_DIR_DLS/nuts-ota.squashfs"

if [[ -f "$OTA_FILE" ]]; then
    puts_info "OTA file found, skipping..."
else
    puts_info "OTA file not found! Downloading OTA file, continuing..."
    MIRROR_LIST=$(grep 'MIRRORLIST=' /tmp/nuts-query.info | sed -e 's/[^=]*=//' -e 's/,/ /g')
    for MIRROR_URL in $MIRROR_LIST; do
        if axel -n 10 -o "$OTA_FILE" "$MIRROR_URL"; then
            echo "Download complete!, continuing..."
            break
        else
            echo "Download from $MIRROR_URL failed. Trying the next mirror..."
        fi
    done
fi


# -- Verify the checksum of the OTA file. Use the checksum from the query file.
# -- Exit if checksum doesn't match.

LOCAL_OTA_SUM=$(md5sum "$NUTS_DIR_DLS"/nuts-ota.squashfs | awk '{ print $1 }')
NQ_OTA_SUM=$(grep -oP '(?<=OTASUM=)[a-f0-9]{32}' /tmp/nuts-query.info)

if [[ "$LOCAL_OTA_SUM" == "$NQ_OTA_SUM" ]]; then
    puts_info "OTA file checksum matches, continuing..."
else
    puts_error "OTA file checksum does not match, quitting."
    rm "$NUTS_DIR_DLS"/nuts-ota.squashfs
    exit 1
fi


# -- Mount the OTA SquashFS.

mount "$NUTS_DIR_DLS"/nuts-ota.squashfs "$NUTS_DIR_SQS" >"$OUTPUT_FILE" 2>&1 || { puts_error "Failed to mount SquashFS file, quitting."; exit 1; }


# -- Now comes the good part; proceed with running rsync and update the current installation.

puts_info "Updating ${CURRENT_DIST^}, continuing..."

dl_file "https://raw.githubusercontent.com/Nitrux/nuts/$NUTS_BRANCH/tmp/rsync-exclude.list" >"$OUTPUT_FILE"

SOURCE_DIR="$NUTS_DIR_SQS"
DESTINATION_DIR="/"
EXCLUDES_FILE="/tmp/rsync-exclude.list"

RSYNC_COMMAND="stdbuf -oL rsync -aDHAXrh --numeric-ids --delete --force --info=progress2 --progress --exclude-from=$EXCLUDES_FILE $SOURCE_DIR/ $DESTINATION_DIR"
eval "$RSYNC_COMMAND" | {
  while IFS= read -r line; do
    echo -ne "\rProgress: $line\033[K"
  done
  echo -e "\n"
}

sync

puts_success "Success! Update has been applied."


# -- Do a cleanup of the synced root.

puts_info "Calling the $TOOL_NAME Cleanup Crew, continuing..."

CLEANUP_SCRIPT_URL="https://raw.githubusercontent.com/Nitrux/nuts/$NUTS_BRANCH/tmp/nuts-ccu"
FILE_LIST_URL="https://raw.githubusercontent.com/Nitrux/nuts/$NUTS_BRANCH/tmp/nuts-cc-file.list"

dl_file "$CLEANUP_SCRIPT_URL" >"$OUTPUT_FILE" || { puts_error "Failed to download the cleanup script, quitting."; exit 1; }
dl_file "$FILE_LIST_URL" >"$OUTPUT_FILE" || { puts_error "Failed to download the file list, quitting."; exit 1; }

if chmod +x /tmp/nuts-ccu && bash /tmp/nuts-ccu >"$OUTPUT_FILE"; then
    puts_success "Cleanup script executed successfully."
else
    puts_error "Something failed in the cleanup script, quitting."
    exit 1
fi

rm -f /tmp/nuts-ccu


# -- Update GRUB.

update-grub >"$OUTPUT_FILE" 2>&1


# -- Unmount all the stuff.

unmount_directory "$NUTS_DIR_SQS" >"$OUTPUT_FILE"
unmount_directory "/home" >"$OUTPUT_FILE"
unmount_directory "/dev" >"$OUTPUT_FILE"


# -- **DO NOT PERFORM ANY FILE OPERATION AFTER THIS POINT**

sync


# -- Finalizing.
# -- Leave the Matri... I mean, the overlay.

exit

#   ====== END ======
