#! /bin/bash

set -e

#   Remove unwanted files and directories.

REMOVE_UNWANTED_FILES='
    /etc/alternatives/README
    /etc/cron.daily/dpkg
    /etc/dpkg/
    /etc/apt/
    /etc/logrotate.d/alternatives
    /etc/logrotate.d/dpkg
    /usr/bin/dpkg
    /usr/bin/dpkg-*
    /usr/bin/update-alternatives
    /usr/libexec/dpkg
    /usr/share/doc/dpkg/
    /usr/share/dpkg/
    /usr/share/lintian/overrides/dpkg
    /usr/share/polkit-1/actions/org.dpkg.pkexec.update-alternatives.policy
    /var/lib/apt/lists
    /var/cache/apt
    /var/lib/dpkg/
    /opt/1
    /opt/2
    /opt/3
	/etc/calamares
	/etc/skel/Desktop/org.nxos.installer.desktop
	/etc/xdg/autostart/calamares-kwin-rules.desktop
	/usr/bin/calamares
	/usr/include/libcalamares/
	/usr/lib/x86_64-linux-gnu/calamares/
	/usr/share/applications/calamares.desktop
	/usr/share/calamares/
	/usr/share/doc/calamares/
	/usr/share/icons/hicolor/scalable/apps/calamares.svg
	/usr/share/lintian/overrides/calamares
	/usr/share/locale/ar/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/as/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ast/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/az/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/az_AZ/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/be/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/bg/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/bn/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ca/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ca@valencia/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/cs_CZ/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/da/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/de/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/el/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/en_GB/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/eo/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/es/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/es_MX/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/et/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/eu/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/fa/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/fi_FI/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/fr/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/fur/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/gl/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/he/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/hi/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/hr/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/hu/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/id/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/is/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/it_IT/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ja/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ko/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/lt/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ml/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/mr/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/nb/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/nl/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/oc/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/pl/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/pt_BR/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/pt_PT/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ro/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/ru/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/si/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/sk/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/sl/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/sq/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/sr/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/sr@latin/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/sv/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/tg/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/th/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/tr_TR/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/uk/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/vi/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/zh_CN/LC_MESSAGES/calamares-python.mo
	/usr/share/locale/zh_TW/LC_MESSAGES/calamares-python.mo
	/usr/share/man/man1/calamares.1.gz
	/usr/share/man/man8/calamares.8.gz
	/usr/share/polkit-1/actions/com.github.calamares.calamares.policy
'

rm -rf "${REMOVE_UNWANTED_FILES//\\n/ }" || true


#   Link kernel image to newer kernel

